name: port
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_database: ^10.4.10
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.6.0
  location: ^5.0.3
  share_plus: ^7.2.2
  sensors_plus: ^4.0.2
  flutter_beep: ^1.0.0
  syncfusion_flutter_gauges: ^24.2.9
  url_launcher: ^6.2.5
  flutter_local_notifications: ^16.3.2
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  workmanager: ^0.5.2
  vibration: ^1.8.4
  provider: ^6.1.1
  flutter_signin_button: ^2.0.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
